# These Quarto configuration parameters will be used during local development, but ignored when
# the content is incorporated into the final CNG tutorial website.
# The final website will be built using the _quarto.yml file in the CNG tutorial repository:
# https://github.com/cloudnativegeo-tutorials/cng-tutorials.github.io/blob/main/_quarto.yml
project:
  type: website

website:
  title: "Tutorial Template"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
